# This is a basic workflow to help you get started with Actions

name: Get boot.img from MIUI Stock ROM

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
    inputs:
     ROM_URL:
      description: 'OTA Url'
      required: true
      default: ''
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
env:
  # https://xiaomifirmwareupdater.com/
  ROM_URL: https://bigota.d.miui.com/V13.0.7.0.SLMCNXM/miui_MUNCH_V13.0.7.0.SLMCNXM_4d8e90d2c3_12.0.zip
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
        
    - name: Init environment
      run: |
        cd ~
        python -m pip install wheel
        python -m pip install protobuf
        python -m pip install bsdiff4
        python -m pip install requests
        
    - name: Clone the tools source code
      run: |
        cd ~
        git clone https://github.com/vm03/payload_dumper.git
        git clone https://github.com/iamleot/transferwee.git
        
    - name: Download ROM
      run: |
        axel -n $(nproc) ${{ github.event.inputs.ROM_URL }} -o rom.zip
        
    - name: Unzip&Remove the ROM
      run: |
        cd ~
        unzip rom.zip -d payload_dumper && rm -v rom.zip
        
    - name: Extract&Zip bootimg from the payload.bin
      run: |
        cd ~
        cd payload_dumper
        # Only boot.img is needed.
        python payload_dumper.py payload.bin --images boot
        cd output && tar -cvzf bootimg.tgz boot.img
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bootimg
        path: payload_dumper/output/boot.img
        
    - name: Upload the bootimg to NetDisks
      run: |
        # WeTransfer
        cd ~ && cd transferwee
        python transferwee.py upload -m $ROM_URL ~/payload_dumper/output/bootimg.tgz
        
        
        # https://github.com/Mikubill/transfer
        cd ~
        curl -sL https://git.io/file-transfer | sh
        # AirPortal
        ./transfer arp ~/payload_dumper/output/bootimg.tgz
        # 奶牛快传
        ./transfer cow ~/payload_dumper/output/bootimg.tgz
        
